<?php

$string = "<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class " . $c . " extends CI_Controller
{
    public \$data;
    function __construct()
    {
        parent::__construct();
        \$this->data=array();
        \$this->load->model('$m');
        \$this->load->library('form_validation');
    }";
$args="";
foreach ($pk as $k=>$row) {
    if($k != sizeof($pk)-1)
        $args .=",";
    $args .= "\$".$row['column_name']."=null";
}

$string .= " 
    public function index_get($args)
    {\n";
foreach ($pk as $row) {
    $string .= "\t\t\$".$row['column_name']."= \$this->get('".$row['column_name']."')?\$this->get('".$row['column_name']."'):\$".$row['column_name'].";\n";
}
foreach ($non_pk as $row) {
    $string .= "\t\t\$".$row['column_name']."= \$this->get('".$row['column_name']."')?\$this->get('".$row['column_name']."'):\"\";\n";
}
$string .="\t\t\$array = array();";
foreach ($all as $row) {
    $string .= "
    \t\tif(\$".$row['column_name'].")
            \$array['".$row['column_name']."'] = \$".$row['column_name'].";";
}
$string .="
       \t\tif(!empty(array_filter(\$array)))
            \$this->response(\$this->".$m."->get_by_cols_array_like(\$array));
        else
            \$this->response(\$this->".$m."->get_all_array());
    }";

$string .= "\n\n}\n\n/* End of file $c_file */
/* Location: ./application/controllers/$c_file */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator ".date('Y-m-d H:i:s')." */
/* http://harviacode.com */";




$hasil_controller = createFile($string, $target . "controllers/" . $c_file);

?>