<?php 

$string = "<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class " . $m . " extends CI_Model
{

    public \$table = '$table_name';
    public \$id = array(";

   foreach($pk as $line_pk)
    $string .= "'".$line_pk['column_name']."',";

    $string .=");
    public \$order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }

    // get all
    function get_all()
    {
        foreach(\$this->id as \$v)
                \$this->db->order_by(\$v, \$this->order);
        return \$this->db->get(\$this->table)->result();
    }
    function get_all_array()
    {
        foreach(\$this->id as \$v)
                \$this->db->order_by(\$v, \$this->order);
        return \$this->db->get(\$this->table)->result_array();
    }

    // get data by id
    function get_by_id(\$ids)
    {
        foreach(\$this->id as \$v)
        \$this->db->where(\$v, \$ids[\$v]);
        
        return \$this->db->get(\$this->table)->row();
    }
    
    // get data by col
    function get_by_cols(\$array = array())
    {
        foreach(\$array as \$col=>\$val)
            \$this->db->where(\$col, \$val);        
        return \$this->db->get(\$this->table)->result();
    }
    // get data by col array
    function get_by_cols_array(\$array = array())
    {
        foreach(\$array as \$col=>\$val)
            \$this->db->where(\$col, \$val);           
        return \$this->db->get(\$this->table)->result_array();
    }
     // get data by cols
    function get_by_cols_array_like(\$cols = array())
    {
        foreach (\$cols as \$col=>\$val)
            \$this->db->like(\$col,\$val);
        return \$this->db->get(\$this->table)->result_array();
    }
     // get data by cols
    function get_by_cols_like(\$cols = array())
    {
        foreach (\$cols as \$col=>\$val)
            \$this->db->like(\$col,\$val);
        return \$this->db->get(\$this->table)->result();
    }
    // get total rows
    function total_rows(\$q = NULL) {
        \$this->db->like('".$pk[0]['column_name']."', \$q);";

foreach ($all as $row) {
    $string .= "\n\t\$this->db->or_like('" . $row['column_name'] ."', \$q);";
}    

$string .= "\n\t\$this->db->from(\$this->table);
        return \$this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data(\$limit, \$start = 0, \$q = NULL) {
            foreach(\$this->id as \$v)
                \$this->db->order_by(\$v, \$this->order);
        
        \$this->db->like('".$pk[0]['column_name']."', \$q);";

foreach ($all as $row) {
    $string .= "\n\t\$this->db->or_like('" . $row['column_name'] ."', \$q);";
}    

$string .= "\n\t\$this->db->limit(\$limit, \$start);
        return \$this->db->get(\$this->table)->result();
    }

    // insert data
    function insert(\$data)
    {
        \$this->db->insert(\$this->table, \$data);
    }

    // update data
    function update(\$ids, \$data)
    {
        foreach(\$this->id as \$v)
        \$this->db->where(\$v, \$ids[\$v]);
        
        \$this->db->update(\$this->table, \$data);
    }

    // delete data
    function delete(\$ids)
    {
        foreach(\$this->id as \$v)
        \$this->db->where(\$v, \$ids[\$v]);
        
        \$this->db->delete(\$this->table);
    }";

if($star === $c){

    $string .= "\n\n    function get_by_external_col_where(\$arr) 
    //array('table',' curr table commun attribut','dist table common attribut','direction','where attribut','where val'
    {
            \$this->db->select('*');
            \$this->db->from(\$this->table.' a'); 
             \$char ='b';
            foreach (\$arr as \$row){
                
                \$this->db->join(\$row['table'].' '.\$char, \$char.'.'.\$row['distcommattr']=a.\$row['currcommattr'], \$row['direction']);
                \$char++;
            }
             \$char ='b';
            foreach (\$arr as \$row){
               
                \$this->db->where(\$row['where'],\$row['whereval']);
                \$char++;
            }            
            \$query = \$this->db->get(); 
            if(\$query->num_rows() != 0)
            {
                return \$query->result_array();
            }
            else
            {
                return false;
            }
    
    ";
   
    $string.="
    }
    ";
}
$string .= "}
/* End of file $m_file */
/* Location: ./application/models/$m_file */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator ".date('Y-m-d H:i:s')." */
/* http://harviacode.com */";




$hasil_model = createFile($string, $target."models/" . $m_file);

?>