<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class CRUD_Utilisateur_model extends CI_Model
{

    public $table = 'utilisateur';
    public $id = 'Matricule';
    public $order = 'ASC';

    function __construct()
    {
        parent::__construct();
    }

    // get all
    function get_all()
    {
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }
    function get_all_array()
    {
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result_array();
    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }
    
    // get data by col
    function get_by_col($col,$val)
    {
        $this->db->where($col, $val);        
        return $this->db->get($this->table)->result();
    }
    // get data by col array
    function get_by_col_array($col,$val)
    {
        $this->db->where($col,$val);
        return $this->db->get($this->table)->result_array();
    }
    // get data by col array
    function get_by_login_mdp($login,$mdp)
    {
        $this->db->where($this->id,$login);
        $this->db->where('Password',$mdp);
        return $this->db->get($this->table)->result_array();
    }

    
    // get total rows
    function total_rows($q = NULL) {
        $this->db->like('Matricule', $q);
	$this->db->or_like('Matricule', $q);
	$this->db->or_like('Nom', $q);
	$this->db->or_like('Prenom', $q);
	$this->db->or_like('Email', $q);
	$this->db->or_like('Password', $q);
	$this->db->or_like('IDUserGroup', $q);
	$this->db->from($this->table);
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL) {
        $this->db->order_by($this->id, $this->order);
        $this->db->like('Matricule', $q);
	$this->db->or_like('Nom', $q);
	$this->db->or_like('Prenom', $q);
	$this->db->or_like('Email', $q);
	$this->db->or_like('Password', $q);
	$this->db->or_like('IDUserGroup', $q);
	$this->db->limit($limit, $start);
        return $this->db->get($this->table)->result();
    }

    // insert data
    function insert($data)
    {
        parent::set_log('insert',$this->table." : ".implode(',',$data));
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data)
    {
        parent::set_log('update',$this->table." : id :".$id." : ".implode(',',$data));
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        parent::set_log('insert',$this->table." : ".$id);
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }
}
/* End of file Utilisateur_model.php */
/* Location: ./application/models/Utilisateur_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2016-06-30 12:16:17 */
/* http://harviacode.com */