<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class CRUD_Ci_nav_items_model extends CI_Model
{

    public $table = 'Ci_nav_items';
    public $id = 'ItemID';
    public $order = 'ASC';

    function __construct()
    {
        parent::__construct();
    }

    // get all
    function get_all()
    {
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }
    function get_all_array()
    {
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result_array();
    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }
    
    // get data by col
    function get_by_col($col,$val)
    {
        $this->db->where($col, $val);        
        return $this->db->get($this->table)->result();
    }
    // get data by col array
    function get_by_col_array($col,$val)
    {
        $this->db->where($col,$val);        
        return $this->db->get($this->table)->result_array();
    }
    
    // get total rows
    function total_rows($q = NULL) {
        $this->db->like('ItemID', $q);
	$this->db->or_like('ItemID', $q);
	$this->db->or_like('ItemName', $q);
	$this->db->or_like('ItemHumanName', $q);
	$this->db->or_like('ItemLink', $q);
	$this->db->or_like('ParentItem', $q);
	$this->db->from($this->table);
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL) {
        $this->db->order_by($this->id, $this->order);
        $this->db->like('ItemID', $q);
	$this->db->or_like('ItemName', $q);
	$this->db->or_like('ItemHumanName', $q);
	$this->db->or_like('ItemLink', $q);
	$this->db->or_like('ParentItem', $q);
	$this->db->limit($limit, $start);
        return $this->db->get($this->table)->result();
    }

    // insert data
    function insert($data)
    {
        parent::set_log('insert',$this->table." : ".implode(',',$data));
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data)
    {
        $this->logs->set_log('update',$this->table." : id :".$id." : ".implode(',',$data));
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->logs->set_log('insert',$this->table." : ".$id);
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }

    function get_by_external_col_where($arr) 
    //array('table',' curr table commun attribut','dist table common attribut','direction','where attribut','where val'
    {
            $this->db->select('*');
            $this->db->from($this->table.' a'); 
             $char ='b';
            foreach ($arr as $row){
                
                $this->db->join($row['table'].' '.$char, $char.'.'.$row['distcommattr']=a.$row['currcommattr'], $row['direction']);
                $char++;
            }
             $char ='b';
            foreach ($arr as $row){
               
                $this->db->where($row['where'],$row['whereval']);
                $char++;
            }            
            $query = $this->db->get(); 
            if($query->num_rows() != 0)
            {
                return $query->result_array();
            }
            else
            {
                return false;
            }
    
    
    }
    }
/* End of file CRUD_Ci_nav_items_model.php */
/* Location: ./application/models/CRUD_Ci_nav_items_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2016-07-01 14:25:29 */
/* http://harviacode.com */